### ISSUE TITLE
History : How it all started

### ISSUE THREAD

**Issue by mimi-uxui-dev** [wizardamigos/wizardamigos.github.io#45]
## `@todo`
- [x] history slide with sub slides to capture the history of wizard amigos and how it all started
  * `@output` :package: [`what have we built hackmd`](https://hackmd.io/@mimiuxui/ryTf3nkW5) from [comment](https://github.com/wizardamigos/wizardamigos.github.io/issues/45#issuecomment-1082415854)
    * next #86
    * next #50
    * next #60
    * next #88
    * next #54
    * next #52
    * next #56
    * next #51
    * next #87
    * next #65
    * next #66
    * next #57
    * next #53
    * next #37
    * next #78
    * next #69
  * `@output` :package: [`history content slides`](https://slides.com/taouskhoudour/palette/fullscreen#/1)
    * next #86
    * next #50
    * next #60
    * next #88
    * next #54
    * next #52
    * next #56
    * next #51
    * next #87
    * next #65
    * next #66
    * next #57
    * next #53
    * next #37
    * next #78
    * next #69

---

## `@info`

A few ideas to have in mind and to focus on while going through the resources below:
* decentralization
* open source
* peer to peer
* self organize
* digital
* community
* it is free and maybe even paid (earn while you learn)

**The History:**
1. the precursor to wizardamigos was codingamigos, which was about a network of coding entrepreneurs working together
  * https://www.facebook.com/codingamigos/
2. it started with helping kids and later refugees to learn the literacy of the future (=programming)
  * https://www.facebook.com/groups/wizardamigos/media
  * https://www.facebook.com/wizardamigos/
3. There have been many websites in the past and the new one should borrow ideas from all of them, especially the first website ever
  * We had probably 5-6 different websites over the years which are all in the github repository,
    * which also has the code for the latest website, which is not the best website we ever had.
  * https://github.com/wizardamigos/wizardamigos.github.io
  * [commit history](https://github.com/wizardamigos/wizardamigos.github.io/commits/master?after=7a738cf46962f194f016624424262204d731b71a+139&branch=master)
4. WizardAmigos started out as a meetup community and many events took place over the last 6-7 years
  * Over the years a few thousand events took place (meetings, codecamps, conferences, etc...) all over the world
    * germany, england, thailand, taiwan, japan, nigeria and the USA.
    * i think the best one was the first one to be honest and we want to return more to that style
    * ...but we want to keep our latest little wizards, the one shown on https://twitter.com/wizardamigos
  * https://meetup.com/wizardamigos
  * https://www.facebook.com/groups/wizardamigos/events
  * https://github.com/wizardamigos/comm-comm
5. We have a youtube channel where we share recorded lessons and also conference presentations
  * https://www.youtube.com/channel/UChZtgbTp4PGDfyKKHcjpp1w
6. We are on social media (facebook page & group, gitter chat, telegram, discord, twitter)
  * https://twitter.com/wizardamigos
  * https://github.com/wizardamigos/profiles
  * https://discord.com/channels/776925030549291059/806366737670733835
  * https://gitter.im/wizardamigosinstitute/program
  * https://web.telegram.org/z/#-1424455348
7. We have a github organisation + up to date skilltree document
  * https://github.com/wizardamigos
  * https://github.com/wizardamigos/skilltree
8. We made many "workshop pages" and a software to connect them into an interactive skilltree
  * the workshop is using the wizardamigos tool to publish workshops and
  * it needs a redesign too and we have a few such tools
  * https://github.com/wizardamigos/wizardamigos-workshop
  * https://github.com/wizardamigos/workshop-buy-bitcoins
  * https://github.com/wizardamigos/wizardamigos-codecamp
  * https://github.com/wizardamigos/codecamp-blockchain
  * https://github.com/wizardamigos/codecamp-company
9. we started chapters all around the world and made it easy for people to make their own chapter
  * https://github.com/wizardamigos/organization
  * https://github.com/wizardamigos/chapter-taipei
  * https://github.com/wizardamigos/chapter-lagos
  * https://github.com/wizardamigos/chapter-berlin
  * https://github.com/wizardamigos/chapter-nashville
10. We made tools for people to create their own workshops
  * https://github.com/wizardamigos/workshop-create-workshop
  * https://github.com/wizardamigos/editor-workshop
  * https://github.com/wizardamigos/editor-codecamp
11. help people start their own projects and become independent
  * https://github.com/wizardamigos/ideas-for-grabs
  * https://github.com/wizardamigos/crypto-amigos
12. planned overview over the earn while you learn system
  * https://github.com/wizardamigos/aybabtu
  * https://github.com/wizardamigos/rails_backend
  * https://github.com/wizardamigos/RepPointsServer
  * https://github.com/wizardamigos/workshop_app
  * https://github.com/wizardamigos/app

**Comment by serapath** [comment]
**result `2022.03.05`**
* [what have we built hackmd](https://hackmd.io/@mimiuxui/ryTf3nkW5)
  * referenced in #45

**Comment by serapath** [comment]
**result `2022.03.05`**
* `result` [`history slides`](https://slides.com/taouskhoudour/palette/fullscreen#/1)
  * added to #45

**Comment by serapath** [comment]
**feedback `2022.03.02`**

> > @mimi-uxui-dev
> > [**worklog video `2022.03.01`**](https://youtu.be/FAi7gsbYYHY) : Aspects slides : What have we built?

as mentioned on discord: play-editor, smartcontract-codes, datdot are out of scope
So the aspects should only include the ones mentioned in the previous feedback

**Comment by serapath** [comment]
> @mimi-uxui-dev 
> [**Worklog Video `2022.03.05`**](https://youtu.be/ePfSssHfWsE) : Everything that should be mentioned in the `What have we built`  slide in the [Wizard Amigos Slide Deck Concept](https://slides.com/taouskhoudour/palette/fullscreen)

> **Results `2022.03.05`** : [`What have we built`](https://hackmd.io/@mimiuxui/ryTf3nkW5)

**Comment by serapath** [comment]
**feedback `2022.03.05`**

> > @mimi-uxui-dev
> > [**Worklog Video `2022.03.05`**](https://youtu.be/ePfSssHfWsE) : Everything that should be mentioned in the `What have we built`  slide in the [Wizard Amigos Slide Deck Concept](https://slides.com/taouskhoudour/palette/fullscreen)
> 
> > **Results `2022.03.05`** : [`What have we built`](https://hackmd.io/@mimiuxui/ryTf3nkW5)


could you please edit the todo list in the first comment to edit and add any todos that come from the feedback below? :-)

---

1. so, is that a hackmd for the history section? if so, maybe a timeline can be added.
or if not - maybe we should think about putting that into the history section (at least the: "what have we built" parts)


**also:**
2. prisonbreak is my own project and its work in progress. its not related to wizardamigos, but the same as everyone is encouraged to share what they are working on, i just shared my own side proeject :slightly_smiling_face:  ...but its not made by wizardamigos.
maybe this can be listed in the history as well as an entry of a community member (me) who started a little project called "prisonbreak" ...its now renamed to "gofree", but thats fine


---

**wanna try to clean things up a bit based on this feedback?**

**more todos to be added to the todo list on top:**

3. do you think we need "long term vision"?

4. what about "show off your profile" vs. "wizardamigos profile"? it sounds to me thats the same thing

5. and "skill-tree" and "workshop skill tree with codecamp areas" is the same thing too

6. and "it's a win-win situation: earn while you learn & give back" might go under "value network sustainability mechanism" ??

7. "what have e built?" sounds to me like "history" ...maybe we should merge that

8. "how to create your virtual code camp" sounds to me like "virtual code camps" and/or "codecamp builder"

9. maybe one more thing would be to go through the old slide decks again (https://github.com/wizardamigos/wizardamigos.github.io/issues/46) and then **LINK ALL** the specific slides which talk about a specific slide that we plan for our new concept slide deck in a github issue or hackmd for each slide we plan to make. That way, when we work on a specific slide for our new slide deck, we can quickly check all the old information we have.
For example the **"paid gig contract chat logs"** thingy is related to the exercise/exam/task/gig list next to each workshop and we have some old slides that talk about it  

---

10. maybe in the wizardamigos concept issue, we could improve the **outline**. It should basically be a "table of content" for the slide decks.
    * what are the main slides?
    * what are the sub slides of the main slides?

...so we can better plan the structure of the slide deck? :slightly_smiling_face: 


---
+1 for grouping the examples of what a workshop or a codecamp or a profile, etc... is and then immediately talking about the workshop builder or codecamp builder or profile maker so people know how to make and update those

in one role they are `users` of the thing
in the other role they are `authors` of the thing :slightly_smiling_face:

**Comment by serapath** [comment]
> @mimi-uxui-dev 
>  **Results** `2022.03.06` : [Commentary and answers](https://hackmd.io/@mimiuxui/HJ3ZgZGZq) for [**Feedback`2022.03.06`**](https://github.com/wizardamigos/wizardamigos.github.io/issues/45#issuecomment-1086772693)

**Comment by serapath** [comment]
**feedback `2022.03.06` part2:**

**+1** to renameing `what have we built` to `what we offer`, then it makes sense to me.

**+1** to the extra todos about the `table of content`. could you add those to the top comment here so we can do them first before the other open tasks we have at the moment? :-)
